In [11]:
using Optim, Random, Zygote
using LinearAlgebra: diag
Random.seed!(0);                            # Fix random seed generator for reproducibility

In [3]:
n = 500                             # Number of observations
nvar = 2                            # Number of variables
β = ones(nvar) * 3.0                # True coefficients
x = [ones(n) randn(n, nvar - 1)]    # X matrix of explanatory variables plus constant
ε = randn(n) * 0.5                  # Error variance
y = x * β + ε;                      # Generate Data

In [4]:
function Log_Likelihood(X, Y, β, log_σ)
    σ = exp(log_σ)
    llike = -n/2*log(2π) - n/2* log(σ^2) - (sum((Y - X * β).^2) / (2σ^2))
    llike = -llike
end

Log_Likelihood (generic function with 1 method)

In [14]:
func = vars -> Log_Likelihood(x, y, vars[1:nvar], vars[nvar + 1])

#13 (generic function with 1 method)

In [6]:
opt = optimize(func, ones(nvar+1))

 * Status: success

 * Candidate solution
    Final objective value:     3.488796e+02

 * Found with
    Algorithm:     Newton's Method

 * Convergence measures
    |x - x'|               = 1.52e-07 ≰ 0.0e+00
    |x - x'|/|x'|          = 5.03e-08 ≰ 0.0e+00
    |f(x) - f(x')|         = 2.18e-11 ≰ 0.0e+00
    |f(x) - f(x')|/|f(x')| = 6.26e-14 ≰ 0.0e+00
    |g(x)|                 = 1.54e-12 ≤ 1.0e-08

 * Work counters
    Seconds run:   0  (vs limit Inf)
    Iterations:    7
    f(x) calls:    31
    ∇f(x) calls:   31
    ∇²f(x) calls:  7


In [7]:
parameters = opt.minimizer

3-element Vector{Float64}:
  2.9675927862968976
  3.0253580418268187
 -0.7211793879066275

In [8]:
parameters[nvar+1] = exp(parameters[nvar+1])

0.4861785246281689

In [15]:
numerical_hessian = hessian(func,parameters)

3×3 Matrix{Float64}:
 189.095         16.3018       -1.78027e-13
  16.3018       201.239        -2.75378e-13
  -1.80425e-13   -2.76772e-13  89.3927

In [16]:
var_cov_matrix = inv(numerical_hessian)

3×3 Matrix{Float64}:
  0.00532553   -0.000431406  9.27693e-18
 -0.000431406   0.00500417   1.45564e-17
  9.41305e-18   1.46228e-17  0.0111866

In [17]:
β = parameters[1:nvar]

2-element Vector{Float64}:
 2.9675927862968976
 3.0253580418268187

In [18]:
temp = diag(var_cov_matrix)
temp1 = temp[1:nvar]

2-element Vector{Float64}:
 0.005325530399036477
 0.005004168944351184

In [19]:
t_stats = β./sqrt.(temp1)


2-element Vector{Float64}:
 40.665196263509166
 42.76719804593069